import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import DesktopNavbar from "@/components/DesktopNavbar";
import MobileNavbar from '@/components/MobileNavbar'
import Footer from "@/components/Footer";
import { Poppins } from 'next/font/google'
import { Rubik } from 'next/font/google'
import { Inter, JetBrains_Mono, Fira_Code
} from 'next/font/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
})
const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choose what you need
  variable: '--font-rubik',
})
const firaCode = Fira_Code({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-fira-code',
})
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const jetbrains = JetBrains_Mono({ subsets: ['latin'], variable: '--font-jetbrains' })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`bg-background text-foreground transition-colors ${poppins.variable} ${rubik.variable} ${inter.variable} ${jetbrains.variable} ${firaCode.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <DesktopNavbar />
          <MobileNavbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
